# Generated by Django 3.0.4 on 2020-04-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20200414_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='maintopic',
        ),
    ]
